#!/usr/bin/env python3
"""
create_model_template.py

Create a uv-based Python package template that conforms to the AbBiBench-style
scoring output contract used by this toolkit.

Usage (run at toolkit repo root):
  python -m abbibench_toolkit.scripts.create_model_template --name MyModel --model-type "Masked LM"

It will create:
  ./models/mymodel/
    pyproject.toml
    README.md
    .gitignore
    src/abbibench_model_mymodel/
      __init__.py
      cli.py
      model.py
      contract.py
      io.py

Then you can:
  cd models/mymodel
  uv run abbibench-mymodel --root-dir ../.. --datasets 1mlc 2fjg
"""

from __future__ import annotations

import argparse
import re
import textwrap
from pathlib import Path


# ----------------------------
# Helpers
# ----------------------------

def slugify(name: str) -> str:
    s = name.strip()
    if not s:
        raise ValueError("Model name must be non-empty")
    # Keep alnum, underscore, hyphen; normalize separators to underscore for package name
    s = re.sub(r"[^\w\-]+", "_", s)
    s = s.strip("_")
    return s


def pkg_name_from_slug(slug: str) -> str:
    # Python import package name
    s = slug.lower().replace("-", "_")
    if not re.match(r"^[a-z_][a-z0-9_]*$", s):
        s = re.sub(r"^[^a-z_]+", "", s)
        s = re.sub(r"[^a-z0-9_]+", "_", s)
    if not s:
        raise ValueError(f"Cannot derive a valid python package name from: {slug!r}")
    return f"abbibench_model_{s}"


def write_file(path: Path, content: str, *, overwrite: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.write_text(content, encoding="utf-8")


# ----------------------------
# Templates
# ----------------------------

def render_pyproject(
    *,
    project_name: str,
    dist_name: str,
    version: str,
    description: str,
    authors: str,
    email: str,
    entrypoint: str,
) -> str:
    """
    Generate pyproject.toml.

    NOTE:
      - We reference toolkit/core via git direct references as requested.
      - Hatchling blocks direct references unless allow-direct-references = true.
    """
    return textwrap.dedent(
        f"""
        [project]
        name = "{dist_name}"
        version = "{version}"
        description = "{description}"
        readme = "README.md"
        requires-python = ">=3.10"
        authors = [{{ name = "{authors}", email = "{email}" }}]
        dependencies = [
          "pandas>=2.0",
          "numpy>=1.24",
          "scipy>=1.10",
          "tyro>=0.8",
          # Toolkit deps via git (direct references).
          "abbibench_toolkit @ git+https://github.com/J-joon/abbibench_toolkit",
          "abbibench_toolkit_core @ git+https://github.com/J-joon/abbibench_toolkit_core",
        ]

        [project.scripts]
        {entrypoint} = "{project_name}.cli:main"

        [build-system]
        requires = ["hatchling>=1.21"]
        build-backend = "hatchling.build"

        [tool.hatch.metadata]
        allow-direct-references = true

        [tool.hatch.build.targets.wheel]
        packages = ["src/{project_name}"]
        """
    ).strip() + "\n"


def render_readme(*, display_name: str, entrypoint: str) -> str:
    return textwrap.dedent(
        f"""
        # {display_name} (AbBiBench Model Package)

        This is a **user model package template** generated by the AbBiBench Toolkit.
        It is designed to follow the toolkit's **scoring output contract** so that:

        - you can run model inference with `uv`,
        - it reads GT CSVs from `<root_dir>/data/binding_affinity/`,
        - it writes prediction CSVs to `<root_dir>/outputs/`,
        - the toolkit can compute correlations / leaderboard downstream.

        ## Repo layout expected

        Your benchmark root directory must contain:

        ```
        <root_dir>/
          data/
            binding_affinity/*.csv
            metadata.json
            complex_structure/*.pdb
          outputs/              # will be created if missing
          artifacts/            # optional
        ```

        ## Quickstart

        From this directory:

        ```bash
        uv run {entrypoint} --root-dir ../.. --datasets 1mlc 2fjg
        ```

        Full dataset run (explicit enumeration):

        ```bash
        uv run {entrypoint} --root-dir ../.. --datasets \\
          1mhp 1mlc 1n8z 2fjg 3gbn_h1 3gbn_h9 4fqi_h1 4fqi_h3 5a12_ang2 aayl50 aayl49 aayl49_ML aayl51 aayl52
        ```

        The command will write files like:

        ```
        <root_dir>/outputs/<CANONICAL_DATASET>_benchmarking_data_{display_name}_scores.csv
        ```

        Dataset ID normalization:
        - This template uses `abbibench_toolkit_core.data.repo.normalize_csv_dataset_id()`.
        - LC/case aliases (e.g., `1mhp -> 1mhp_LC`, `aayl51 -> aayl51_LC`) are defined in toolkit-core.

        ## What you need to implement

        Edit `src/.../model.py`:

        - implement `Model.score_dataframe(df, dataset_id)` to return a 1D array-like of floats aligned to df row-order.
        - the output is written to the `log-likelihood` column by default.
        - you may ignore GT columns except for inputs you need.

        ## Notes on contract columns

        - Required GT column: `binding_score`
        - Recommended ID columns are carried into outputs if present:
          `heavy_chain_seq`, `light_chain_seq`, `mut_heavy_chain_seq`, `mut_light_chain_seq`, `antigen_seq`, `mut_antigen_seq`
        - Output score column default: `log-likelihood`

        """
    ).strip() + "\n"


def render_gitignore() -> str:
    return textwrap.dedent(
        """
        .venv/
        __pycache__/
        *.pyc
        *.pyo
        *.pyd
        .pytest_cache/
        .mypy_cache/
        .ruff_cache/
        *.egg-info/
        dist/
        build/
        """
    ).strip() + "\n"


def render_init() -> str:
    return "__all__ = []\n"


def render_contract_py(*, display_name: str) -> str:
    return textwrap.dedent(
        f"""
        from __future__ import annotations

        from dataclasses import dataclass
        from pathlib import Path

        import pandas as pd
        from abbibench_toolkit_core.data.repo import BENCHMARKING_SUFFIX, normalize_csv_dataset_id


        # ----------------------------
        # Contract constants
        # ----------------------------

        # Output column name used for correlation (default).
        SCORE_COLUMN = "log-likelihood"

        # Preferred identifier columns (keep any that exist in the GT CSV).
        ID_COLUMN_CANDIDATES: tuple[str, ...] = (
            "heavy_chain_seq",
            "light_chain_seq",
            "mut_heavy_chain_seq",
            "mut_light_chain_seq",
            "antigen_seq",
            "mut_antigen_seq",
        )

        # Ground-truth column required by the benchmark.
        GT_COLUMN = "binding_score"

        # Output file name suffix.
        OUTPUT_SUFFIX = "_scores.csv"


        def resolve_dataset_id(dataset_id: str) -> str:
            \"\"\"
            Map user-facing dataset id to the canonical on-disk dataset id.

            This MUST match toolkit-core behavior so that:
              - GT lookup succeeds
              - output filenames are canonical
            \"\"\"
            return normalize_csv_dataset_id(dataset_id)


        def select_id_columns(df: pd.DataFrame) -> list[str]:
            \"\"\"Select identifier columns to carry into outputs (intersection of candidates and df columns).\"\"\"
            return [c for c in ID_COLUMN_CANDIDATES if c in df.columns]


        def gt_csv_path(root_dir: Path, dataset_id: str) -> Path:
            ds = resolve_dataset_id(dataset_id)
            return root_dir / "data" / "binding_affinity" / f"{{ds}}{{BENCHMARKING_SUFFIX}}"


        def output_csv_path(root_dir: Path, dataset_id: str, model_id: str) -> Path:
            ds = resolve_dataset_id(dataset_id)
            return root_dir / "outputs" / f"{{ds}}_benchmarking_data_{{model_id}}_scores.csv"


        @dataclass(frozen=True)
        class ContractInfo:
            model_id: str = "{display_name}"
            score_column: str = SCORE_COLUMN
        """
    ).strip() + "\n"


def render_io_py() -> str:
    return textwrap.dedent(
        """
        from __future__ import annotations

        from pathlib import Path
        import pandas as pd


        def write_scores_csv(df: pd.DataFrame, path: Path, *, overwrite: bool = False) -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists() and not overwrite:
                raise FileExistsError(f"Refusing to overwrite existing output: {path}")
            df.to_csv(path, index=False)
        """
    ).strip() + "\n"


def render_model_py() -> str:
    return textwrap.dedent(
        """
        from __future__ import annotations

        from dataclasses import dataclass
        import numpy as np
        import pandas as pd


        @dataclass
        class Model:
            \"\"\"
            Implement your model here.

            Contract:
              - score_dataframe(df, dataset_id) returns a 1D array-like of floats
                aligned to df row-order.
              - The caller writes these scores to the 'log-likelihood' column by default.

            Practical guidance:
              - For sequence-based models: read columns like heavy_chain_seq/light_chain_seq/mut_* from df.
              - For structure-based models: the toolkit-core repo provides metadata + PDB paths; you can
                use abbibench_toolkit_core.data.repo.AbBiBenchRepo if your model needs structures.
            \"\"\"

            def score_dataframe(self, df: pd.DataFrame, dataset_id: str) -> np.ndarray:
                # TODO: Replace this stub with real inference.
                #
                # Example:
                #   inputs = df["heavy_chain_seq"].tolist()
                #   scores = my_model_loglikelihood(inputs)
                #   return np.asarray(scores, dtype=float)
                #
                return np.zeros(len(df), dtype=float)
        """
    ).strip() + "\n"


def render_cli_py(*, display_name: str) -> str:
    return textwrap.dedent(
        f"""
        from __future__ import annotations

        from dataclasses import dataclass
        from pathlib import Path
        from typing import Sequence

        import pandas as pd
        import tyro

        from .contract import ContractInfo, GT_COLUMN, select_id_columns, gt_csv_path, output_csv_path
        from .io import write_scores_csv
        from .model import Model


        @dataclass(frozen=True)
        class Args:
            \"\"\"Run model inference and emit contract-compliant score CSVs.\"\"\"

            # Benchmark root (contains ./data and ./outputs)
            root_dir: Path = Path("../..")

            # Dataset ids to score (user-facing ids; normalized via toolkit-core)
            datasets: Sequence[str] = (
                "1mhp",
                "1mlc",
                "1n8z",
                "2fjg",
            )

            # Override model id used in output filename
            model_id: str = "{display_name}"

            # Score column name in output CSV (default: log-likelihood)
            score_column: str = "log-likelihood"

            # Overwrite existing outputs
            overwrite: bool = False

            # Emit extra debug prints
            verbose: bool = True


        def _load_gt(root_dir: Path, dataset_id: str) -> pd.DataFrame:
            p = gt_csv_path(root_dir, dataset_id)
            if not p.exists():
                raise FileNotFoundError(f"Missing GT CSV: {{p}}")
            df = pd.read_csv(p)
            if GT_COLUMN not in df.columns:
                raise KeyError(f"Missing required column '{{GT_COLUMN}}' in {{p}}. cols={{list(df.columns)}}")
            return df


        def run_one(
            *,
            root_dir: Path,
            dataset_id: str,
            model: Model,
            info: ContractInfo,
            score_column: str,
            overwrite: bool,
            verbose: bool,
        ) -> Path:
            gt = _load_gt(root_dir, dataset_id)
            id_cols = select_id_columns(gt)

            if not id_cols and verbose:
                print(f"[WARN] No ID columns found in GT for {{dataset_id}}. Proceeding with row-order outputs only.")

            scores = model.score_dataframe(gt, dataset_id)
            if len(scores) != len(gt):
                raise ValueError(
                    f"Score length mismatch: got {{len(scores)}} scores but GT has {{len(gt)}} rows for {{dataset_id}}"
                )

            out = pd.DataFrame()
            for c in id_cols:
                out[c] = gt[c]
            # Keep binding_score in output for compatibility with external scripts.
            out[GT_COLUMN] = gt[GT_COLUMN]
            out[score_column] = scores

            out_path = output_csv_path(root_dir, dataset_id, info.model_id)
            write_scores_csv(out, out_path, overwrite=overwrite)

            if verbose:
                print(f"[OK] wrote {{out_path}} (rows={{len(out)}} cols={{list(out.columns)}})")
            return out_path


        def main() -> None:
            a = tyro.cli(Args)
            root = a.root_dir.resolve()
            (root / "outputs").mkdir(parents=True, exist_ok=True)

            model = Model()
            info = ContractInfo(model_id=a.model_id)

            for ds in a.datasets:
                run_one(
                    root_dir=root,
                    dataset_id=ds,
                    model=model,
                    info=info,
                    score_column=a.score_column,
                    overwrite=a.overwrite,
                    verbose=a.verbose,
                )


        if __name__ == "__main__":
            main()
        """
    ).strip() + "\n"


# ----------------------------
# Main
# ----------------------------

def entrypoint() -> None:
    ap = argparse.ArgumentParser(description="Generate a uv-based AbBiBench model package template.")
    ap.add_argument("--name", required=True, help="Model display name (used in filenames, e.g., ProteinMPNN, MyModel)")
    ap.add_argument("--model-type", default="Other", help='Model type label (e.g., "Masked LM", "Inverse Folding")')
    ap.add_argument("--target-dir", default="models", help="Where to create the model package (default: ./models)")
    ap.add_argument("--repo-root", default=".", help="Toolkit repo root (default: current directory)")
    ap.add_argument("--author", default="Jaejoon Kim", help="Author name for pyproject metadata")
    ap.add_argument("--email", default="jjkim030309@gmail.com", help="Author email for pyproject metadata")
    ap.add_argument("--version", default="0.1.0", help="Initial package version")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite files if they already exist")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()
    if not (repo_root / "data").exists():
        raise FileNotFoundError(f"repo_root does not look like the benchmark root (missing ./data): {repo_root}")

    display_name = args.name.strip()
    slug = slugify(display_name)
    pkg = pkg_name_from_slug(slug)

    target_dir = Path(args.target_dir).resolve()
    pkg_dir = target_dir / slug.lower().replace("-", "_")

    dist_name = f"abbibench-model-{slug.lower().replace('_','-')}"
    entrypoint_name = f"abbibench-{slug.lower().replace('_','-')}"

    description = f"AbBiBench user model package: {display_name} ({args.model_type})"

    # Files
    pyproject = render_pyproject(
        project_name=pkg,
        dist_name=dist_name,
        version=args.version,
        description=description,
        authors=args.author,
        email=args.email,
        entrypoint=entrypoint_name,
    )
    readme = render_readme(display_name=display_name, entrypoint=entrypoint_name)
    gitignore = render_gitignore()

    init_py = render_init()
    contract_py = render_contract_py(display_name=display_name)
    io_py = render_io_py()
    model_py = render_model_py()
    cli_py = render_cli_py(display_name=display_name)

    # Write
    write_file(pkg_dir / "pyproject.toml", pyproject, overwrite=args.overwrite)
    write_file(pkg_dir / "README.md", readme, overwrite=args.overwrite)
    write_file(pkg_dir / ".gitignore", gitignore, overwrite=args.overwrite)

    src_dir = pkg_dir / "src" / pkg
    write_file(src_dir / "__init__.py", init_py, overwrite=args.overwrite)
    write_file(src_dir / "contract.py", contract_py, overwrite=args.overwrite)
    write_file(src_dir / "io.py", io_py, overwrite=args.overwrite)
    write_file(src_dir / "model.py", model_py, overwrite=args.overwrite)
    write_file(src_dir / "cli.py", cli_py, overwrite=args.overwrite)

    print("\nCreated model package template:")
    print(f"  {pkg_dir}")
    print("\nNext steps:")
    print(f"  cd {pkg_dir}")
    print(f"  uv run {entrypoint_name} --root-dir ../.. --datasets 1mlc 2fjg")
    print("\nThen implement your real model in:")
    print(f"  {src_dir / 'model.py'}")


if __name__ == "__main__":
    entrypoint()

